arb-dir: l10n
template-arb-file: app_ar.arb
output-localization-file: app_localizations.dart # flutter gen-l10n

# Configuration for generating JSON file with untranslated messages
untranslated-messages-file: untranslated_messages.json