name: pedagogue
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter
  intl: any

  # UI/UX
  flutter_spinkit: 
  fluttertoast: 
  shimmer: 

  # LANGUAGE
  flag: 

  # Firebase
  firebase_core: 
  cloud_firestore: 
  firebase_storage: 
  firebase_messaging: 

  # MEDIA
  photo_view: 
  image_picker: 
  native_video_view:
  flutter_cache_manager: 

  # NETWORKING & STORAGE
  shared_preferences: 
  cached_network_image: 
  provider: 
  http: 
  http_parser: 
  mime: 

  # INTERACTIVE SVG
  xml: 
  path_drawing: 

  # OTHER
  flutter_local_notifications: 
  calendar_view: 
  loader_overlay: 
  get: 
  webview_flutter: 
  syncfusion_flutter_calendar: 
  flutter_gemini: 
  syncfusion_flutter_pdf: 
  open_file: 
  path_provider: 
  path_provider_platform_interface: 
  im_stepper: 
  customizable_counter:
  flutter_rating_bar: 
  another_stepper: 
  stepper_list_view: 
  url_launcher: 
  stepper_a: 
  video_player: 
  chewie: 
  file_picker: 
  flutter_pdfview: 
  youtube_player_flutter: 
  carousel_slider: 
  flutter_slimy_card: 
  curved_carousel: 
  stop_watch_timer: 
  pdf: 
  flutter_inappwebview: 
  syncfusion_flutter_core: 
  syncfusion_flutter_charts: 
  printing: 
  syncfusion_flutter_sliders: 
  syncfusion_flutter_gauges:
  audioplayers:
  permission_handler: 
  flutter_downloader: 
  connectivity_plus: 
  wakelock: ^0.6.2
  multi_dropdown: ^2.1.4
  flutter_resizable_container: ^0.4.1
  flutter_launcher_icons: ^0.13.1
  country_list_pick: ^1.0.1+6
  flick_video_player: ^0.7.0
  camera: ^0.11.0
  dart_openai: ^5.1.0
  envied: ^0.5.4+1
  csv: ^6.0.0
  

  
 
 

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_icons: #  dart run flutter_launcher_icons
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/staff/
    - assets/human_body/
    - assets/technical_drawing/
    - assets/technical_drawing/athletics/
    - assets/technical_drawing/basketball/
    - assets/technical_drawing/football/
    - assets/technical_drawing/handball/
    - assets/technical_drawing/rugby/
    - assets/technical_drawing/tennis/
    - assets/technical_drawing/volleyball/
    - assets/JannaLT-Regular.ttf